apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "gateway-operator.konghq.com/v1alpha1",
          "kind": "GatewayConfiguration",
          "metadata": {
            "name": "kong"
          },
          "spec": {
            "controlPlaneDeploymentOptions": {
              "env": [
                {
                  "name": "TEST_VAR",
                  "value": "TEST_VAL"
                }
              ]
            },
            "dataPlaneDeploymentOptions": {
              "env": [
                {
                  "name": "TEST_VAR",
                  "value": "TEST_VAL"
                }
              ]
            }
          }
        }
      ]
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.22.0
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v3
  name: operator.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: ControlPlane is the Schema for the controlplanes API
      displayName: Control Plane
      kind: ControlPlane
      name: controlplanes.gateway-operator.konghq.com
      version: v1alpha1
    - description: DataPlane is the Schema for the dataplanes API
      displayName: Data Plane
      kind: DataPlane
      name: dataplanes.gateway-operator.konghq.com
      version: v1alpha1
    - kind: GatewayConfiguration
      name: gatewayconfigurations.gateway-operator.konghq.com
      version: v1alpha1
  description: Kong Operator for Kubernetes
  displayName: Kong
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - apps
          resources:
          - deployments
          verbs:
          - create
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - apps
          resources:
          - deployments/status
          verbs:
          - get
        - apiGroups:
          - ""
          resources:
          - services
          verbs:
          - create
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - services/status
          verbs:
          - get
        - apiGroups:
          - gateway-operator.konghq.com
          resources:
          - controlplanes
          verbs:
          - create
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - gateway-operator.konghq.com
          resources:
          - controlplanes/finalizers
          verbs:
          - update
        - apiGroups:
          - gateway-operator.konghq.com
          resources:
          - controlplanes/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - gateway-operator.konghq.com
          resources:
          - dataplanes
          verbs:
          - create
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - gateway-operator.konghq.com
          resources:
          - dataplanes/finalizers
          verbs:
          - update
        - apiGroups:
          - gateway-operator.konghq.com
          resources:
          - dataplanes/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - gateway-operator.konghq.com
          resources:
          - gatewayconfigurations
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - gateway.networking.k8s.io
          resources:
          - gatewayclasses
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - gateway.networking.k8s.io
          resources:
          - gateways
          verbs:
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - gateway.networking.k8s.io
          resources:
          - gateways/finalizers
          verbs:
          - update
        - apiGroups:
          - gateway.networking.k8s.io
          resources:
          - gateways/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: gateway-operator-controller-manager
      deployments:
      - label:
          control-plane: controller-manager
        name: gateway-operator-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              annotations:
                kubectl.kubernetes.io/default-container: manager
              labels:
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=0
                image: gcr.io/kubebuilder/kube-rbac-proxy:v0.8.0
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                  protocol: TCP
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 5m
                    memory: 64Mi
              - args:
                - --health-probe-bind-address=:8081
                - --metrics-bind-address=127.0.0.1:8080
                command:
                - /manager
                image: ghcr.io/kong/gateway-operator:main
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 10m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
              securityContext:
                runAsNonRoot: true
              serviceAccountName: gateway-operator-controller-manager
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: gateway-operator-controller-manager
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - networking
  - gateway
  - ingress
  - kong
  - kubernetes
  - go
  links:
  - name: Operator
    url: https://operator.domain
  maturity: alpha
  provider:
    name: Kong Inc.
    url: https://konghq.com
  version: 0.0.1
